svgp:
  _target_: models.svgp.SVGP
  _convert_: all
  inducing_points:
    _target_: torch.rand
    size:
      # - 1
      - 3
      # - 2
      # - 128 # num_inducing
      - 256 # num_inducing
      - 1
  mean_module:
    _target_: gpytorch.means.ConstantMean
    batch_shape: 3
    # _target_: gpytorch.means.ZeroMean
    # batch_shape:
    #   - 3
  covar_module:
    _target_: gpytorch.kernels.ScaleKernel
    base_kernel:
      _target_: gpytorch.kernels.RBFKernel
      ard_num_dims: 1
      batch_shape:
        - 3
    batch_shape:
      - 3
  learn_inducing_locations: false
  device: "cpu"
  likelihood:
    _target_: gpytorch.likelihoods.MultitaskGaussianLikelihood
    num_tasks: 3
