_target_: models.gp.SVGPTransitionModel
_convert_: all
likelihood:
  _target_: gpytorch.likelihoods.MultitaskGaussianLikelihood
  num_tasks: ${state_dim}
mean_module:
  _target_: gpytorch.means.ConstantMean
  batch_shape: ${state_dim}
covar_module:
  _target_: gpytorch.kernels.ScaleKernel
  base_kernel:
    _target_: gpytorch.kernels.RBFKernel
    ard_num_dims: ${input_dim}
    batch_shape:
      - ${state_dim}
  batch_shape:
    - ${state_dim}
num_inducing: 128
batch_size: 64
# num_iterations: 5000
num_iterations: 2000
# num_iterations: 5
learning_rate: 0.01
delta_state: True
num_workers: 1 # TODO what should I set this to?
