defaults:
  # Use slurm on cluster or local?
  # - override hydra/launcher: submitit_local
  # - override hydra/launcher: local
  - override hydra/launcher: lumi
  # - override hydra/launcher: slurm
  # - override hydra/launcher: slurm_cpu
  # Disable logging by Hydra
  # - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

dataset: "FMNIST"
# dataset: "CIFAR10"
model_name: "CNN"

device: ???
output_dim: ???
batch_size: 512
lr: 1e-3
n_epochs: 500
# n_epochs: 1
double: True

num_workers: 8
# num_workers: 1

logging_epoch_freq: 10
random_seed: 117

sfr:
  _target_: src.nn2svgp.ntksvgp.NTKSVGP
  _convert_: all
  # network: ???
  # prior: ???
  likelihood: ${likelihood}
  output_dim: ${output_dim}
  num_inducing: 128
  dual_batch_size: 1000
  jitter: 1e-4
  device: ${device} # TODO should this always be cpu??

prior:
  _target_: src.nn2svgp.priors.Gaussian
  # params: ???
  delta: 0.0001

likelihood:
  _target_: src.nn2svgp.likelihoods.CategoricalLh

# network:
#   _target_: src.sl.train.get_model
#   model_name: "CNN"
#   ds_train: ${dataset}

# dataset_name:
# dataset:
#   _target_: src.sl.train.get_dataset
#   dataset: "FMNIST"
#   double: ${double}
#   device: ${device}

wandb:
  group: ${dataset}
  entity: "aidanscannell"
  project: "nn2svgp-sl"
  use_wandb: True
  run_name: delta=${prior.delta}-lr=${lr}-seed=${random_seed}-${now:%Y-%m-%d_%H-%M-%S}
  # run_name: ${alg_name}-${online_update_freq}-${agent.horizon}-${random_seed}-${now:%Y-%m-%d_%H-%M-%S}
  tags:
    - "delta=${prior.delta}"
    - "m=${sfr.num_inducing}"
    - "dataset=${dataset}"
  #   - "env=${env.env_name}-${env.task_name}"
  #   - "alg=${alg_name}"
  #   - "online_update_freq=${online_update_freq}"

hydra:
  job:
    chdir: False
  run:
    dir: ""
