_target_: src.models.transitions.svgp.init
_convert_: all
svgp:
  _target_: models.svgp.SVGP
  inducing_points:
    _target_: torch.rand
    size:
      # - ${state_dim}
      - 1
      - 500 # num_inducing
      - ${input_dim}
      # - ${state_dim}
      # - 500 # num_inducing
      # - ${input_dim}
  mean_module:
    _target_: gpytorch.means.ConstantMean
    batch_shape: ${state_dim}
  covar_module:
    _target_: gpytorch.kernels.ScaleKernel
    base_kernel:
      _target_: gpytorch.kernels.RBFKernel
      ard_num_dims: ${input_dim}
      batch_shape:
        - ${state_dim}
    batch_shape:
      - ${state_dim}
  learn_inducing_locations: true
likelihood:
  _target_: gpytorch.likelihoods.MultitaskGaussianLikelihood
  num_tasks: ${state_dim}
# learning_rate: 0.05
learning_rate: 0.1
batch_size: 64
num_epochs: 300
# num_workers: 1 # TODO what should I set this to?
# wandb_loss_name: "model/transition_loss"
wandb_loss_name: "transition/loss"
early_stopper:
  _target_: utils.EarlyStopper
  patience: 50
  min_delta: 0
device: ${device} # TODO should this always be cpu??
