# _target_: dm_control.suite.load
# domain_name: "cartpole"
# task_name: "swingup"
# task_kwargs:
#   random: ${random_seed}
# visualize_reward: false

_target_: src.rl.utils.env.make_env
env_name: "cheetah"
task_name: "run"
seed: ${random_seed}
action_repeat: 2
