_target_: models.transition.build_SVGPTransitionModel
# _convert_: all
svgp:
  inducing_points:
    _target_: torch.rand
    size:
      - ${state_dim}
      - 500 # num_inducing
      - ${input_dim}
  mean_module:
    _target_: gpytorch.means.ConstantMean
    batch_shape: ${state_dim}
  covar_module:
    _target_: gpytorch.kernels.ScaleKernel
    base_kernel:
      _target_: gpytorch.kernels.RBFKernel
      ard_num_dims: ${input_dim}
      batch_shape:
        - ${state_dim}
    batch_shape:
      - ${state_dim}
  learn_inducing_locations: true
likelihood:
  _target_: gpytorch.likelihoods.MultitaskGaussianLikelihood
  num_tasks: ${state_dim}
# learning_rate: 0.05
learning_rate: 0.1
batch_size: 64
num_workers: 1 # TODO what should I set this to?
wandb_loss_name: "Transition model loss"
