defaults:
  # - model: laplace
  # - model: svgp
  - reward_model: svgp
  - transition_model: svgp
  # - model: world_model
  # - model_new: world_model
  # - agent: ddpg
  - agent: mppi
  - env: cartpole_swingup
  # - env: cartpole_balance
  # - env: Pendulum-v1
  # - env: CartPole-v1
  # - planner: mppi
  # - planner: cem
  # - model: probabilistic_ensemble
  # Use slurm on cluster or local?
  # - override hydra/launcher: submitit_local
  # - override hydra/launcher: local
  - override hydra/launcher: slurm
  # Disable logging by Hydra
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

state_dim: ???
action_dim: ???
input_dim: ???
output_dim: ???
device: ???

alg_name: "mppi-svgp"
random_seed: 42

init_random_episodes: 10
num_train_episodes: 2000
# episode_length: 1000
episode_length: 100
update_every_steps: 2

eval_episode_freq: 10
# eval_episode_freq: 2
# save_video: true
save_video: false

replay_buffer_capacity: 100000
save_buffer: false
buffer_scratch_dir: "/tmp/"
batch_size: 512

wandb:
  group: ${env.env_name}-${env.task_name}
  # group: ${env.env_name}
  entity: "aidanscannell"
  project: "bayesian-model-based-rl-with-fast-updates"
  use_wandb: True
  run_name: ${alg_name}-${random_seed}-${now:%Y-%m-%d_%H-%M-%S}
  tags:
    - "random_seed=${random_seed}"
    - "env=${env.env_name}-${env.task_name}"
    - "alg=${alg_name}"

hydra:
  job:
    chdir: False
  run:
    dir: ""
