defaults:
  - submitit_slurm

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
account: project_462000217
partition: standard-g # Partition (queue) name
timeout_min: 500
cpus_per_task: 6
gpus_per_node: 1
tasks_per_node: 1
mem_gb: null
nodes: 1
name: ${hydra.job.name}
qos: null
comment: null
constraint: null
exclude: null
gres: null
cpus_per_gpu: null
gpus_per_task: null
mem_per_gpu: null
mem_per_cpu: null
signal_delay_s: 120
max_num_timeout: 0
additional_parameters: {}
array_parallelism: 256
setup: null
