# defaults:
#   - submitit_slurm

# _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
# # submitit_folder: ${hydra.sweep.dir}/.submitit/%j
# # timeout_min: 360 # 6 hours
# # cpus_per_task: 6 # 6 cpus
# # gpus_per_node: 0
# # tasks_per_node: 1
# # nodes: 1
# # name: ${hydra.job.name}
# # comment: null
# # exclude: null
# # cpus_per_gpu: null
# # gpus_per_task: null
# # mem_per_cpu: 10000 # 1000MB of memory
# # signal_delay_s: 600
# # max_num_timeout: 20
# # additional_parameters: {}
# # array_parallelism: 256
# # setup: []

# timeout_min: 720
# # cpus_per_task: 1
# cpus_per_task: 6
# gpus_per_node: 0
# tasks_per_node: 1
# # tasks_per_node: 6
# mem_gb: 4
# nodes: 1
# name: ${hydra.job.name}

defaults:
  - submitit_slurm

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
# # submitit_folder: ${hydra.sweep.dir}/.submitit/%j
# timeout_min: 1440 # 72 hours
# # cpus_per_task: 4
# # gpus_per_node: 4
# tasks_per_node: 1
# nodes: 1
# name: ${hydra.job.name}
# comment: null
# exclude: null
# # cpus_per_gpu: null
# # gpus_per_task: null
# signal_delay_s: 600
# max_num_timeout: 20
# additional_parameters: {}
# array_parallelism: 256
# setup: []
# constraint: "volta"
# mem_gb: 10
# # mem_gb: 50
# gres: gpu:1

# partition: standard-g
# account: project_462000183
# timeout_min: 500 # 72 hours
# # time: 10:00:00
# ntasks: 1
# cpus-per-task: 8
# gpus-per-task: 1
# mem: 10G
# array: 0-12

# output: "nn2svgp.o%j" # Name of stdout output file
# error: "nn2svgp.e%j" # Name of stderr error file
# nodes: 2 # Total number of nodes
# ntasks-per-node: 6 # 8 MPI ranks per node, 128 total (16x8)
# gpus-per-node: 1 # Allocate one gpu per MPI rank
# # time1-12:00:00       # Run time (d-hh:mm:ss)
# # timeout_min: 500
# # mail-user=

account: project_462000183
partition: standard-g # Partition (queue) name
timeout_min: 500
cpus_per_task: 6
gpus_per_node: 1
tasks_per_node: 1
mem_gb: null
nodes: 1
name: ${hydra.job.name}
qos: null
comment: null
constraint: null
exclude: null
gres: null
cpus_per_gpu: null
gpus_per_task: null
mem_per_gpu: null
mem_per_cpu: null
signal_delay_s: 120
max_num_timeout: 0
additional_parameters: {}
array_parallelism: 256
setup: null
srun_args: null
