_target_: torchrl.modules.CEMPlanner
env: ${model}
# planning_horizon: 10
planning_horizon: 2
# optim_steps: 11
optim_steps: 5
# num_candidates: 7
num_candidates: 3
top_k: 3
reward_key: 'reward'
# reward_key: 'expected_reward'
action_key: 'action'
